package fx.chart;

public enum ChartType {

    SCATTER,
    POINCARE,
    LINE,
    SMOOTH_LINE,
    AREA,
    SMOOTH_AREA,
    BAR,
    BUBBLE,
    DONUT,
    RADAR_POLYGON,
    SMOOTH_RADAR_POLYGON,
    RADAR_SECTOR,
    POLAR,
    SMOOTH_POLAR, HORIZON, SMOOTHED_HORIZON, MATRIX_HEATMAP, LINE_DELTA, SMOOTH_LINE_DELTA, NESTED_BAR, PARALLEL_COORDINATES,
    RIDGE_LINE, MULTI_TIME_SERIES, SMOOTHED_MULTI_TIME_SERIES, PANEL_BAR_CHART, PREDICTION_TIMESERIES
}
